### ISSUE TITLE
[bug] node dashboard only shows latest instance

### ISSUE THREAD

**Issue by uhthomas** [dotdc/grafana-dashboards-kubernetes#102]
### Describe the bug

Some panels are using `node` to filter, and others are using a hidden `instance` variable (`	label_values(node_uname_info{nodename=~"(?i:($node))"}, instance)`). If a node changes its IP, then some panels will look normal and others will be missing data.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/d462f6ae-e4ca-4c48-bba1-3727bf332673)

### How to reproduce?

1. Collect node metrics.
2. Change IP of node.
3. Observe the node dashboard has some unaffected panels, and others which only show the latest 'instance'.

### Expected behavior

It should probably show all instances of a node.

**Comment by dotdc** [comment]
Hi @uhthomas,

I've been thinking about this and don't see a fix for this one.
The node / instance hack was used to have convenient names while using the dashboard, I'd like to keep it that way.

For me, a node changing IP is a rare corner case, but I guess it depends on your setup.

How often do you have IP changes on your nodes?

**Comment by dotdc** [comment]
Documented in [34a469f](https://github.com/dotdc/grafana-dashboards-kubernetes/commit/34a469f1f2ff208d3bf3097a21b61ec42c4df817)
