### ISSUE TITLE
Publish tag to make update automation possible

### ISSUE THREAD

**Issue by davinkevin** [dotdc/grafana-dashboards-kubernetes#107]
### Describe the enhancement you'd like

As a `renovate` user (but this applies to all similar tools), I would like to leverage our system to upgrade automatically our dashboards. 

Currently we have no solution to be automatically notified about an update or a change from this project. A solution based on `git` tag could do the job perfectly. 

Tags don't have to be semantic or logical, a simple tag every months is a perfect and valid solution.

### Additional context

… nothing specific. Let me know if you have any question.

PS: Your dashboards are really amazing, thank you for this work!

**Comment by dotdc** [comment]
Thanks for bringing this subject back to the table @davinkevin.
This was briefly discussed in the past and I think it's a good idea.
Will add a semantic releaser to the project when I have time 👍

**Comment by dotdc** [comment]
@davinkevin Just added a semantic releaser, going forward, every dashboard change will result in a release.
Will probably force a `v2.0.0` tag on HEAD soon to better fit project's history, but will respect semver after that. :+1:

**Comment by davinkevin** [comment]
🥳
