### ISSUE TITLE
[bug] Fix node_* metrics on k8s-views-global.json

### ISSUE THREAD

**Issue by dotdc** [dotdc/grafana-dashboards-kubernetes#111]
### Describe the bug

Currently, there is no job label selector in k8s-views-global.json.

History: 
- A hardcoded job label was set to `node-exporter` in [#36](https://github.com/dotdc/grafana-dashboards-kubernetes/pull/36) for `node_*` metrics
- They were after removed in [#49](https://github.com/dotdc/grafana-dashboards-kubernetes/pull/49) to work with Grafana Agent

Adding a job variable for `node_*` metrics should fix the issue.

@uhthomas @tlemarchand Can you both try the version in https://github.com/dotdc/grafana-dashboards-kubernetes/pull/110 to make sure it works on your side ?

**Comment by tlemarchand** [comment]
@dotdc  It works for me.
Thanks a lot for this fix !

**Comment by uhthomas** [comment]
@dotdc I think it's weird to support monitoring nodes which are not part of the Kubernetes cluster, but this seems like a reasonable change and should accommodate both.
