### ISSUE TITLE
[bug] kubernetes-views-namespaces: created_by_name doesn't work

### ISSUE THREAD

**Issue by dohnto** [dotdc/grafana-dashboards-kubernetes#116]
### Describe the bug

The `created_by_name` variable doesn't work as expected and doesn't offer a drill down:
<img width="611" alt="image" src="https://github.com/user-attachments/assets/172cbbbb-7a49-4310-bb76-730cee9b58ed">

I found out that this is caused by the variable selector `container!=""` ([source link](https://github.com/dotdc/grafana-dashboards-kubernetes/blob/9cd553a98227d0819ea9ef743289e1a49cd6121b/dashboards/k8s-views-namespaces.json#L2278)):
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/339441cf-8a8f-4ebd-a54c-d452ae29b08f">

As `kube_pod_info` metric doesn't contain the `container` label ([official docs](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/workload/pod-metrics.md)).

When I remove the `container!=""` selector, the variable will start working again.

**Comment by dotdc** [comment]
Hi @dohnto,

That's interesting, it works on my side:

![image](https://github.com/user-attachments/assets/387ab2e9-b3bf-473c-9a82-4c9847cf4ae5)

Can you give more information on your setup ? (kubernetes version, kubernetes distribution, kube-prometheus-stack version...)

I'll make additional tests and see what I can do.

**Comment by dotdc** [comment]
I'm pretty sure we can delete it from the `created_by` variable as you suggested.
Do you want to open a PR for this?

**Comment by dotdc** [comment]
Done in https://github.com/dotdc/grafana-dashboards-kubernetes/pull/117
