### ISSUE TITLE
[enhancement] Dashboard that shows container versions over time

### ISSUE THREAD

**Issue by dkrizic** [dotdc/grafana-dashboards-kubernetes#123]
### Describe the enhancement you'd like

Thanks you for your excellent work. It would be a good addition to have an overview of which images and version of images are being used and especially over time, so when did an update happen.

**Comment by dotdc** [comment]
Hi @dkrizic,

Something like this?

![2024-10-02 22 01 08 localhost 09b2013104c6](https://github.com/user-attachments/assets/622695a8-6b84-4b8b-bf9a-4e72857738dd)


Query:
```
count(rate(container_cpu_usage_seconds_total{namespace=~"$namespace", image!="", cluster="$cluster"}[$__rate_interval])) by (image)
```

**Comment by dkrizic** [comment]
I ask myself if the image name and the tag can be splitted. So basically it would be nice to have the possibility to drill down like

Namespace -> Deployment/Cronjob/Statefulset/Daemonset -> Used image -> Used imaged versions

To answer questions like:

* What version does this deployment run currently?
* What was it running last week?
* Since when does version X run?

**Comment by dotdc** [comment]
I don't think it's worth splitting the image name and version.

Here's another version with an updated Grafana image as example:
![Screenshot From 2024-10-03 07-43-22](https://github.com/user-attachments/assets/4827514a-e736-4e36-b576-24dd42b2bcbb)

**Comment by dotdc** [comment]
Added the panel in [v2.4.0](https://github.com/dotdc/grafana-dashboards-kubernetes/releases/tag/v2.4.0).
Thank you for the idea @dkrizic !
