### ISSUE TITLE
[bug] Incorrect CPU Usage by Instance display

### ISSUE THREAD

**Issue by guessi** [dotdc/grafana-dashboards-kubernetes#124]
### Describe the bug

Incorrect display
Unit: `Percent (0.0-1.0)`
![image](https://github.com/user-attachments/assets/83bd67a9-70e0-4666-b7bb-0dd3cb5c939a)

Correct display
Unit: `Percent (0-100)`
![image](https://github.com/user-attachments/assets/1cbb657a-3f10-4988-b05b-147af442e069)

### How to reproduce?

Import current latest [k8s-system-api-server.json](https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-system-api-server.json) and find `API Server - CPU Usage by instance` panel.

### Expected behavior

It should have no percentage > 100 display.

**Comment by dotdc** [comment]
Hi @guessi,

Thank you for opening this issue and the pull request.
I don't see such error on my side, and I wonder if the issue is not related to the panel query or duplicate series on your setup.
Do you think you could compare the panel query with your pods resource usage to see if it matches?

Something like:

![2024-10-02 21 45 29 localhost 38221db47cb0](https://github.com/user-attachments/assets/a2f4c3f3-8e12-4ce7-98e4-c6ecbff129f2)

Query (update label like pod name to match your setup):
```
sum(rate(container_cpu_usage_seconds_total{namespace="kube-system", pod=~"kube-apiserver-k8s-control-plane-001", image="", cluster=""}[$__rate_interval]))
```

**Comment by guessi** [comment]
Hi @dotdc,

Allow me to provide more background story.

For most circumstances, both `percentunit (Percent (0.0-1.0))` and `percent (Percent (0-100))` are okay. However, if you try to stress test on ***Multi-core*** API servers, `percentunit` would show wrong metrics, that would be a problem.

Please verify again with current latest Grafana (11.2.2) and please be sure to put stress to your API server and make sure it is running with high loading at the time. I believe you should observe the issue on your side as well.

**Comment by dotdc** [comment]
I compared with the pods view dashboard which uses another metric (`container_cpu_usage_seconds_total`) and got the same percentage on my side. No matter the load, numbers should be the same, can you compare them on your side?

![Screenshot From 2024-10-03 07-24-01](https://github.com/user-attachments/assets/f19dcdb4-1ea5-4f7d-a207-1abd77fd938a)

**Comment by guessi** [comment]
Note that it is about [k8s-system-api-server.json](https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-system-api-server.json) and the dashboard `API Server`, `CPU Usage by instance` panel.

**Comment by guessi** [comment]
Please note the key is that the issue is about **_Multi-core_** API servers monitoring.

**Comment by dotdc** [comment]
I understand the difference between the two units, I'm just not convinced by this change from what I see on my setups.

Can you share: 
- Kubernetes distribution and version
- Version of kube-prometheus-stack (or deployment method with involved components versions)
- `proccess_cpu_seconds_total` is a host based metrics, do you have other instances running on the same host? (including VMs/Containers)
- Do you see the same value in both dashboard ([k8s-system-api-server.json](https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-system-api-server.json) and [k8s-views-pods.json](https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-views-pods.json))
- Can you share a series sample of `proccess_cpu_seconds_total` related to the apiserver in Grafana explore (need the full line so as text ideally)

**Comment by dotdc** [comment]
> **_Multi-core_** API servers monitoring.

Can you expand on this please?

**Comment by guessi** [comment]
I'm running with Amazon EKS 1.31 (just released few days ago), all components are current latest version, but actually the matrix of {version/distro/cloud} doesn't matter. Even you are running self-managed Kubernetes cluster, I believe it could easily be reproduced by running API servers with a multi-core machine.

**Comment by dotdc** [comment]
I've been able to reproduce and it turns out that my initial results were wrong because I tested it with the empty image label (https://github.com/dotdc/grafana-dashboards-kubernetes/pull/122) which introduced a regression that was later removed in https://github.com/dotdc/grafana-dashboards-kubernetes/pull/126.

Thank you for pointing that out and sorry for the delay and the confusion.
