### ISSUE TITLE
[enhancement] View of containers not running

### ISSUE THREAD

**Issue by dkrizic** [dotdc/grafana-dashboards-kubernetes#127]
### Describe the enhancement you'd like

I my normal cluster I usually have containers that are either

* Running
* Completed (Jobs, CronJobs)

I recently had the following state

* ErrImgPull
* Pending

I could not find this information anywhere in the dashboards. I would like to have a view of "abnormal state", abnormal being everything else than Running and Completed. That would make sense in the Global dashboard.

**Comment by dotdc** [comment]
Hi @dkrizic,

Added a panel in the namespaces dashboard (https://github.com/dotdc/grafana-dashboards-kubernetes/commit/6c07ab20fcdd2e064d0108458626522a344cab47), but I think you should rely on an alerting rule for that.

Let me know if this solves your issue.

**Comment by dkrizic** [comment]
I agree with the alert rule, but still nice to have this in the overview when looking into the problems.
