### ISSUE TITLE
[bug] Some dashboards are broken on high pods count

### ISSUE THREAD

**Issue by maxpain** [dotdc/grafana-dashboards-kubernetes#129]
### Describe the bug

Hello. We have a lot of short-lived pods in our clusters. It's also a problem for frequent CronJobs.

https://github.com/user-attachments/assets/7b9e0606-a46f-45e9-af56-f9721c0f19ea

**Comment by EladAviczer** [comment]
Have you tried increasing the CPU resources allocated to Prometheus?

**Comment by maxpain** [comment]
@EladAviczer did you watch the video?

**Comment by EladAviczer** [comment]
*victoriaMetrics

**Comment by dotdc** [comment]
Hi @maxpain,

The `created_by` variable was introduced to enable filtering on deployments, but if there are too many pods, you'll up end with a `422 Unprocessable Entity error` as you just experienced.

I’ll check if there’s a better solution, but removing the `created_by` variable might work better in your case.

**Comment by hagen1778** [comment]
> I’ll check if there’s a better solution, but removing the created_by variable might work better in your case.

Could just setting `Custom all value` to wildcard for this variable help? 
<img width="309" alt="image" src="https://github.com/user-attachments/assets/6e221ae0-48ba-465f-b06b-ca2de3b98c30">
Then, when `all` is selected, dashboard won't try sending a request with thousands options - it would just send `pod=~".*"` instead. This would be helpful for any type of datasource there.

**Comment by dotdc** [comment]
@maxpain Should be better with dashboards released in [v2.5.3](https://github.com/dotdc/grafana-dashboards-kubernetes/releases/tag/v2.5.3).

**Comment by maxpain** [comment]
thanks!
