### ISSUE TITLE
The k8s-views-namespaces.json dashboard does not work

### ISSUE THREAD

**Issue by piratetm** [dotdc/grafana-dashboards-kubernetes#14]
![image](https://user-images.githubusercontent.com/40763772/177775003-90ef6753-ef3e-48b5-ac0b-8b022c34f5fd.png)
Grafana version is v8.2.4

Help please

**Comment by dotdc** [comment]
Hi @piratetm,

Can you try using Grfana 8.5.6 ?

If it still doesn't work, can you provide more information on your setup:
- kube-prometheus-stack version
- kubernetes distribution
- kubernetes version
- ...

**Comment by dotdc** [comment]
Closing, let me know if you have the same issue using the last version of the dashboards & kube-prometheus-stack.
