### ISSUE TITLE
Network - Packets Dropped not working.

### ISSUE THREAD

**Issue by Jojoooo1** [dotdc/grafana-dashboards-kubernetes#23]
It seems that the network view at the pod level is not working.

![Screenshot from 2022-08-05 16-48-57](https://user-images.githubusercontent.com/17641873/183150387-4a27dbab-665c-4306-8db6-3fb56e04e100.png)

**Comment by dotdc** [comment]
Hi @Jojoooo1,
It is working according to the screenshot (yellow lines), you just don't have any errors right now.
If the query wasn't working, you will either have a "No data" message or a red exclamation mark.

**Comment by dotdc** [comment]
Closing

**Comment by Jojoooo1** [comment]
Hi @dotdc :) my prometheus is actually returning some metrics for this pod this is why it was strange to see no data on the graph

**Comment by dotdc** [comment]
You have data, the yellow line is data (with 0 as values) . You just don't have any errors right now that's why the error rate is 0 (this is the expected behavior).
