### ISSUE TITLE
[bug] some panels not displyaing correctly on white background

### ISSUE THREAD

**Issue by clementnuss** [dotdc/grafana-dashboards-kubernetes#27]
### Describe the bug

Hi,

I'm using those dashboards with Grafana using the light theme (easier on my eyes), and some panels are not displaying properly. e.g.:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/2116997/193195041-df647987-39fc-4e9c-adc5-823e2cca3419.png">

this can be fixed by setting the color mode of the panel to `None` instead of `Value`

<img width="402" alt="Screenshot 2022-09-30 at 07 13 22" src="https://user-images.githubusercontent.com/2116997/193195172-4251a8b3-001d-40a9-9b5d-f386addf44c1.png">

### How to reproduce?

1. turn on light mode for Grafana.
2. check the `Kubernetes / Views / Global` panel

### Expected behavior

the text/values should be readable even with the light theme

**Comment by dotdc** [comment]
Hi @clementnuss,

Thank you for the bug report.
I will test with and get back to you during the day.

**Comment by clementnuss** [comment]
wait a few minutes, I'm writing a PR for that :) going through the dashboards and changing the `colorMode` to `None` where it needs to be changed

**Comment by dotdc** [comment]
Fixed by https://github.com/dotdc/grafana-dashboards-kubernetes/pull/28
