### ISSUE TITLE
[bug]  Wrong query on the Network - Bandwidth panel

### ISSUE THREAD

**Issue by germetist** [dotdc/grafana-dashboards-kubernetes#29]
### Describe the bug

On `Kubernetes / Views / Pods` dashboard on `Network - Bandwidth` panel wrong query of Transmitted

It is
```
- sum(rate(container_network_receive_bytes_total{namespace="$namespace", pod="$pod"}[$__rate_interval]))
```
Should be 
```
- sum(rate(container_network_transmit_bytes_total{namespace="$namespace", pod="$pod"}[$__rate_interval]))
```

### Additional context

https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-views-pods.json#L1417

**Comment by dotdc** [comment]
Fixed by https://github.com/dotdc/grafana-dashboards-kubernetes/pull/30
Thanks for your contribution!
