### ISSUE TITLE
[bug] bad_data: invalid parameter 'query': 1:109: parse error: bad duration syntax: "1m0"

### ISSUE THREAD

**Issue by flowerpp** [dotdc/grafana-dashboards-kubernetes#33]
### Describe the bug

Hi 
I try my grafana version 8.1.8,  9.1.0 , 9.2.4,   but have a same error as follows.

Thanks for advance!

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/3191305/202089501-5e01ea8d-94c6-4892-bc85-8a328294a0d2.png">

<img width="685" alt="image" src="https://user-images.githubusercontent.com/3191305/202089554-41298432-42ba-4549-a8f8-b0e78aa9e74e.png">

**Comment by dotdc** [comment]
Hi, I don't have the same error, did you edited the dashboard?
According to the error, It seems the rate interval is incorrect, it should be `1m` instead of `1m0`.

Dashboard default is to use `$__rate_interval` variable instead of a fixed interval.

**Comment by dotdc** [comment]
Closing
