### ISSUE TITLE
[bug] Global Network Utilization

### ISSUE THREAD

**Issue by reefland** [dotdc/grafana-dashboards-kubernetes#35]
### Describe the bug

On my simple test cluster, I have no issues with the Global Netowrk Utilization, but on my production cluster that does cluster and host networking the numbers are crazy:

![image](https://user-images.githubusercontent.com/16230914/209415727-abaf886f-d538-4a60-b68e-1a1c3279cc35.png)

No way I have sustained rates like that. I think this is related to the metric:

`sum(rate(container_network_receive_bytes_total[$__rate_interval]))`

If I look at `rate(container_network_receive_bytes_total[30s])`, I get:

```
{id="/", interface="cni0", job="kubernetes-cadvisor"} | 2041725438.15131
{id="/", interface="enp1s0", job="kubernetes-cadvisor"} | 4821605692.45648
{id="/", interface="flannel.1", job="kubernetes-cadvisor"} | 337125370.2678834
```

I'm not sure what to actually look at here. I tried `sum(rate(node_network_receive_bytes_total[$__rate_interval]))` and I get a reasonable traffic graph:

![image](https://user-images.githubusercontent.com/16230914/209416144-aca5b786-0205-4dea-8050-18f58b2e1ff3.png)

This is 5 nodes, pretty  much at idle.   Showing I/O by instance:

![image](https://user-images.githubusercontent.com/16230914/209417138-a21801d4-a557-405b-b04f-5678df2cbcc9.png)

Here is BTOP+ on `k3s01` running for a bit, lines up very will with data above:
![image](https://user-images.githubusercontent.com/16230914/209417207-71065711-559a-4c80-a2eb-e2c76299653a.png)

**Comment by dotdc** [comment]
Hi @reefland,
Thanks for reporting this, I will check on my setup and come back to you.

**Comment by dotdc** [comment]
Here's a first fix: https://github.com/dotdc/grafana-dashboards-kubernetes/commit/6e3a73fdeae4ee99b248b3f78044215ab249ead7

This should have been done when the labels got dropped from kube-prometheus-stack.

Let me know if this solves the issue.

**Comment by reefland** [comment]
Global Network Utilization looks reasonable now, by Namespace is still bonkers:
![image](https://user-images.githubusercontent.com/16230914/210461060-9d4c61f5-9864-4275-bda4-6f9bf1000763.png)

**Comment by reefland** [comment]
After re-working my install, this looks different now. I get the per namespace metrics now.

![image](https://user-images.githubusercontent.com/16230914/211176588-c75db738-bef3-4e0e-9a4b-64e4b4a7081b.png)

But still puzzled on why the per namespace numbers are way higher than the global numbers.  My assumption is this is the difference between local and host networking?  Here is the zoomed in version of by Namespaces:

![image](https://user-images.githubusercontent.com/16230914/211176814-4246f9ec-f1ec-4985-a0e6-eaeaf8c8ddff.png)

The top 3 are ones that either use Host Networking or talk external to the cluster:  ceph is just cluster to cluster member, but uses host networking so I can allow non-cluster computer to use the Rook-Ceph storage if needed.  The CSI is using storage to a TrueNAS server and the Monitoring namespace is the only namespace still using that CSI (everything else is using Ceph).

I suspect there is some double counting going on.. the CSI is twice the PVC usage.. the containers virtual adapter and physical adapter? If I look at the underlying query `rate(container_network_receive_bytes_total[2m0s])` with just the by namespace part removed, you see the results include multiple network adapters (virtual and physical) and I think this is where the double-counting comes in.

Trying to make the query simpler, I limit it to one namespace and one node of that namespace `rate(container_network_receive_bytes_total{namespace="democratic-csi",instance="k3s01"}[2m0s])`.  You can see the multiple interfaces being counted:

![image](https://user-images.githubusercontent.com/16230914/211177165-d200fde1-9c51-43dd-80dc-c0aa821237ee.png)

If I make the global based on `container_network_receive_bytes_total` and `container_network_transmit_bytes_total`, at least it matches:

![image](https://user-images.githubusercontent.com/16230914/211177264-4988685b-29b9-407a-8cdf-c36e62726456.png)

So maybe that is the way to do global? :man_shrugging:

**Comment by dotdc** [comment]
Agree, something is probably counted more than once, and this is probably because of the current label selectors.
Sometimes, we need to narrow the scope, but in this case, I can't filter on the interfaces names because they are subject to change depending on the setup…

I made the benches a long time ago and it seemed correct, so I either missed something, or something changed since then. 

I don't have the time to make the measures right now, but will have a look when I can.

**Comment by dotdc** [comment]
Hi @reefland, sorry for the delay, will look at it this week!

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
- [](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
[](url)

**Comment by jud336** [comment]
### [](url)

**Comment by dotdc** [comment]
Because the `device` names can be anything, It's not a good idea to filter on them, but I tried to exclude common virtual patterns to make the panels slightly more clear (we could build upon that).

Check out the latest version that sum by `device`, and let me know what you think.

Commit: https://github.com/dotdc/grafana-dashboards-kubernetes/commit/3e717213bc6784449629d083ede134bcb168b8a0
