### ISSUE TITLE
Running pods panel in Global dashboard

### ISSUE THREAD

**Issue by mashun4ek** [dotdc/grafana-dashboards-kubernetes#5]
Currently, "Running Pods" panel uses the expression `sum(kube_pod_container_info)`, which sums the containers, but not the pods. I believe the metric `kube_pod_info` would be the best for this panel.

Should be updated here: https://github.com/dotdc/grafana-dashboards-kubernetes/blob/793cb68b3c8474dca19f686c63e11f96b01f13b4/dashboards/k8s-views-global.json#L868-L881

P.S. Thank you for the dashboards, they look awesome!

**Comment by dotdc** [comment]
It's fixed, thank you @mashun4ek for reporting the issue!
Glad to see the dashboards are usefull :wink:
