### ISSUE TITLE
[bug] default resolution is too low

### ISSUE THREAD

**Issue by uhthomas** [dotdc/grafana-dashboards-kubernetes#50]
### Describe the bug

The default resolution of 30s is too low and renders some dashboards with "No Data". This is likely because I'm using Grafana Mimir, as opposed to a standard Prometheus install. 

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/8f348c66-3ed1-406d-a17c-9a4465117b03)

### How to reproduce?

1. Collect metrics with Grafana Mimir.
2. Load the dashboard.

### Expected behavior

Changing the resolution from 30s to 1m shows the data as expected.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/e9c28977-e39f-4948-a8a4-a39fb30b5240)

**Comment by dotdc** [comment]
I added the resolution variable in an attempt to see spikes in a very specific case.
I think it would make more sense to remove it completely and let `$__rate_interval` do its job.

In case anyone needs it, it's pretty easy to edit a panel to add it back.

**Comment by uhthomas** [comment]
For example, these two panels behave differently without an explicit resolution. They both use `auto` min resolution and the rate interval, but one renders okay and the other doesn't.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/d9d1a08e-5d2d-4857-aef3-2b8c4a039645)

**Comment by uhthomas** [comment]
Hmm, Grafana agent is configured with a 15s scrape interval.

https://github.com/uhthomas/automata/blob/ed25c6b7a525182f1c626f1fb2feda99b268db65/k8s/unwind/grafana_agent/grafana_agent_list.cue#L22

Though, changing the value to `1m` in Grafana for the datasource does seem to fix things! Thanks for the pointers and the help.

**Comment by dotdc** [comment]
Interesting... 
Will add this to the "known issues" list. Feel free to share any further knowledge you may have on this issue in the future.
