### ISSUE TITLE
[bug]  Dashboard kubernetes-views-pods shows unexpected values for memory requests / limits

### ISSUE THREAD

**Issue by danielrolfes2307** [dotdc/grafana-dashboards-kubernetes#54]
### Describe the bug

First of all: amazing dashboards...Thanks a ton :)

The panel "Resources by container" in the "kubernetes-views-pods"  uses the metrics
kube_pod_container_resource_requests{namespace="$namespace", pod="$pod", unit="byte"}
kube_pod_container_resource_usage{namespace="$namespace", pod="$pod", unit="byte"}

Unfortunately this leads to unexpected values as the label "resource" in these metrics can have the values "memory" and "ephemeral_storage" and counts them together.

### Expected behavior

The metrics should probably  be:
kube_pod_container_resource_requests{namespace="$namespace", pod="$pod", unit="byte", resource="memory"}
kube_pod_container_resource_usage{namespace="$namespace", pod="$pod", unit="byte", resource="memory"}

**Comment by dotdc** [comment]
Hi @danielrolfes2307,

Thanks for reporting this!
I don't have any series where `resource` has `ephemeral_storage` set on my side.
Could you please share related details of your setup so we can have the information on this issue?

I assume you have the same behaviour in `k8s-views-global.json` and `k8s-views-namespaces.json` ?

**Comment by dotdc** [comment]
@danielrolfes2307 https://github.com/dotdc/grafana-dashboards-kubernetes/pull/55 should fix the issue.
Let me know

**Comment by danielrolfes2307** [comment]
@dotdc 
This fixes it...Thanks :)
