### ISSUE TITLE
[bug] Node metrics names on AWS EKS nodes mismatch 

### ISSUE THREAD

**Issue by Piroddi** [dotdc/grafana-dashboards-kubernetes#56]
### Describe the bug

The metrics for `kube_node_info` & `node_uname_info` produce different names for nodes, resulting in the Node dashboard not working. 

Eg:

node_uname_info:
  -  nodename="ip-10-10-11-100.ec2.internal"
  
kube_node_info
  -  node="ip-10-10-10-110.us-east-2.compute.internal"
  
 
 Node exporter version: 1.3.1
 Kube state metrics version: 2.5.0
 

I acknowledge this is not a bug on the dashboard itself but rather the naming standards on the different metric exporters. 

However just wanted to know if other aws eks users are experiencing the same issue before I start manually editing the dashboard in an attempt to get the dashboards working.  

Thanks

**Comment by dotdc** [comment]
Hi @Piroddi,

Did you tried the [workaround mentioned in the doc](https://github.com/dotdc/grafana-dashboards-kubernetes#broken-panels-on-k8s-views-nodes-due-to-the-nodename-label)?

**Comment by Piroddi** [comment]
Hi @dotdc  

Sorry I did not see this before. Works perfectly. Thank you.
