### ISSUE TITLE
Total pod RAM request usage & Total Pod RAM limit usage gauge is showing wrong value

### ISSUE THREAD

**Issue by noor-muradi** [dotdc/grafana-dashboards-kubernetes#57]
### Describe the bug

First of all I want to thank you for your effort for creating amazing Grafana dashboard for K8s I have deployed Prometheus helm chart stack and passed the dashboard provider value to values.yaml, everything went smooth except one issue that I am facing in  /kubernetes/view/pods, which total pod RAM request usage and Total RAM limit usage gauge is showing wrong value as you can see in the below screenshot, I wonder if someone can help me to fix it.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/24589033/908285fd-d2e1-4abb-ab46-5ac713954202)

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/24589033/52b85e43-6366-43a9-a3fb-221198d46a0c)

**Comment by dotdc** [comment]
Hi @noor-muradi,

Thank you for reporting this issue.

The problem was accidentaly introduced in https://github.com/dotdc/grafana-dashboards-kubernetes/pull/55, and will be fixed in https://github.com/dotdc/grafana-dashboards-kubernetes/pull/56.

**Comment by noor-muradi** [comment]
@dotdc It is resolved now, thanks.
