### ISSUE TITLE
[bug] Namespace dashboard shows double resource usage

### ISSUE THREAD

**Issue by uhthomas** [dotdc/grafana-dashboards-kubernetes#60]
### Describe the bug

The cumulative resource usage in the namespace seems to be 1.25 cpu and 2.5Gi (I changed the two graphs to stack), but it appears as 2.5 cpu and 5Gi respectively.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/6472e3f2-8a88-4822-b95c-eac163b48aa7)

I imagine the queries need the label selector `image!=""`.

### How to reproduce?

N/A

### Expected behavior

N/A

### Additional context

N/A

**Comment by maulik9211** [comment]
I actually had to go and add divide by 2 to fix this. Then it matched exactly with my k9s readings. 
<img width="1496" alt="Screenshot 2024-12-06 at 1 48 03 PM" src="https://github.com/user-attachments/assets/4c21b549-5782-4d84-a6b9-fc60e171a48b">

**Comment by uhthomas** [comment]
> I actually had to go and add divide by 2 to fix this. Then it matched exactly with my k9s readings. 
> 
>  
> 
> <img width="1496" alt="Screenshot 2024-12-06 at 1 48 03 PM" src="https://github.com/user-attachments/assets/1bc022b1-54b7-45bf-99b9-87041ab3438b">
> 
> 
> 
> 

Sounds like an issue with your monitoring setup? I would fix that rather than doing strange hacks on queries.
