### ISSUE TITLE
[bug] Trivy Operator Dashboard: The Prometheus data source variable is not used everywhere

### ISSUE THREAD

**Issue by omallo** [dotdc/grafana-dashboards-kubernetes#65]
### Describe the bug

There are panels in the Trivy Operator dashboard which do not properly use the Prometheus data source variable.

### How to reproduce?

1. Import the dashboard
2. Change between Prometheus data sources in the global variable filter
3. See that the "Vulnerability count per image and severity in $namespace namespace" panel does not pick up the Prometheus data source correctly

### Expected behavior

The global Prometheus data source variable should be applied to all panels.

### Additional context

Here are the places I spotted where the Prometheus data source variable is not used:

https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-addons-trivy-operator.json#L785
https://github.com/dotdc/grafana-dashboards-kubernetes/blob/master/dashboards/k8s-addons-trivy-operator.json#L882

**Comment by dotdc** [comment]
Hi @omallo,

Thank you for the bug report, https://github.com/dotdc/grafana-dashboards-kubernetes/pull/66 should fix the issue.

Let me know

**Comment by omallo** [comment]
@dotdc , many thanks for the rapid fix! I just tested it and it works fine :)

Do you plan on uploading the new dashboard revision to the Grafana website as well? If so, please let me know once done so that we can consume the new dashboard directly from there. In the meantime, we'll consume it from GitHub.

**Comment by dotdc** [comment]
@omallo Of course, should be good now!
