### ISSUE TITLE
[bug] `kube-prometheus-stack` installation steps broken

### ISSUE THREAD

**Issue by inssein** [dotdc/grafana-dashboards-kubernetes#67]
This worked for me in the past, but I am building a new k3s cluster and I can't install it with the previous documentation: https://github.com/dotdc/grafana-dashboards-kubernetes#install-with-helm-values.

The error I get is a little specific to me since I am using terraform:
```
│ Error: unable to build kubernetes objects from release manifest: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string
│
│   with module.monitoring.helm_release.prometheus-stack,
│   on ../modules/monitoring/main.tf line 2, in resource "helm_release" "prometheus-stack":
│    2: resource "helm_release" "prometheus-stack" {
```

I tried to read https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml, but looks like a few things have changed.

**Comment by dotdc** [comment]
Hi @inssein,

Just tested it using kube-prometheus-stack 51.3.0, and it works fine, I assume this is an issue with your setup.

I'll close this for now, but fill free to open a new one if you find an issue with the dashboards or the configuration examples.

Grafana values : https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

**Comment by inssein** [comment]
Ah damn, sorry about that. Likely is a bug somewhere in the terraform setup.
