### ISSUE TITLE
[bug] "FS - Device Errors" query in Nodes dashboard is not scoped

### ISSUE THREAD

**Issue by l2dy** [dotdc/grafana-dashboards-kubernetes#68]
### Describe the bug

In k8s-views-nodes.json, the "FS - Device Errors" query is `sum(node_filesystem_device_error) by (mountpoint)`, which aggregates data from the entire datasource.

### Expected behavior

`{instance="$instance"}` should be added to the query.

**Comment by dotdc** [comment]
Hi @l2dy,
Thank you for reporting the issue, this should be fixed by #69!
