### ISSUE TITLE
[bug] Variable `job` in Kubernetes / Views / Nodes is not referenced

### ISSUE THREAD

**Issue by l2dy** [dotdc/grafana-dashboards-kubernetes#71]
### Describe the bug

Grafana shows an exclamation mark on the variable `job`.

**Comment by dotdc** [comment]
Hi @l2dy,
This is probably due to your setup, try to find what's missing, maybe a relabelling rule?

**Comment by l2dy** [comment]
> Hi @l2dy, This is probably due to your setup, try to find what's missing, maybe a relabelling rule?

It's not a problem with the data. By not referenced, I mean "This variable is not referenced by any variable or dashboard.", which is similar to an unused variable in code and should be removed.

**Comment by dotdc** [comment]
Sorry, I didn't get it!
Thank you for letting me know, will make a PR to fix the issue.
