### ISSUE TITLE
getting Failed to upgrade legacy queries e.replace is not a function

### ISSUE THREAD

**Issue by anannaya** [dotdc/grafana-dashboards-kubernetes#73]
### Describe the bug

 Tried to import the dashboards in grafana 7.4.5 , getting  **Failed to upgrade legacy queries e.replace is not a function**
 error

**Comment by dotdc** [comment]
Hi @anannaya,
These dashboards use recent Grafana features that could sacrifice backward compatibility.
I believe you use Grafana 7.4.5 for a reason, but I can only suggest you to upgrade to version 9 or 10.
Closing this issue because supporting older Grafana versions is out of scope, sorry.
