### ISSUE TITLE
[bug] Pod memory / cpu requests and limits invalid values with Opencost installed

### ISSUE THREAD

**Issue by nlamirault** [dotdc/grafana-dashboards-kubernetes#75]
### Describe the bug

Hi,
On the "Pod" dashboard, we have invalid values for pod resources (cpu and memory): values doubled
![Edit-panel-Kubernetes-Views-Pods-kubernetes-Dashboards-Grafana](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/29233/89376ebe-a071-437c-8e69-a1f266b94e58)

We have correct values when we specify the `kube-state-metrics` job.

![Edit-panel-Kubernetes-Views-Pods-Copy-kubernetes-Dashboards-Grafana](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/29233/8219477b-92c0-402c-9760-804c6b431ae7)

The Prometheus metrics:
![Prometheus-Time-Series-Collection-and-Processing-Server (4)](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/29233/f92019b8-95e0-45be-9fbd-6118bbf1a85a)

**Comment by alexiiiiiiiiiiiiiii** [comment]
Hello,
There is the same bug when kubecost is installed and you solve this bug the same way

**Comment by dotdc** [comment]
Hi @nlamirault,

I guess you have the same behaviour in the other dashboards, at least in Global?
Could you share the other values of the `job` label?
Also, can you give a little more details on your Prometheus setup/stack?

A way to fix this is bringing back the `job` variable in all the dashboards.

**Comment by dotdc** [comment]
@nlamirault Can you test the version in https://github.com/dotdc/grafana-dashboards-kubernetes/pull/76 ?
