### ISSUE TITLE
Error updating options: Unexpected token p in JSON at position 4

### ISSUE THREAD

**Issue by i5Js** [dotdc/grafana-dashboards-kubernetes#8]
Hi, 

I'm trying to add the dashboard, but I'm having this error message in all of them:

`"Error updating options: Unexpected token p in JSON at position 4"`

Could you please help me?

Many thanks

**Comment by dotdc** [comment]
Hi @i5Js,

What Grafana version are you using and how are you importing the dashboards?
Can you try using 9.0.2 and/or 8.5.6?

**Comment by i5Js** [comment]
Hey dotdc, thanks for your answer. I've deployed with helm so I guess it's using 9.02... because I didn't specify a version tag

**Comment by i5Js** [comment]
Of course: I'm using 9.01 (14e988bd22). I've tried to import them using the grafana ID or uploading the json files. But with the same error message.

**Comment by i5Js** [comment]
I've just updated to 9.0.2, but nothing has changed.

**Comment by i5Js** [comment]
Update: I've redeployed everything from scratch. Now, I'm not having any error message. Just "NO DATA" but I guess it's a matter of time :)
