### ISSUE TITLE
[bug] CPU dashboard can report negative values

### ISSUE THREAD

**Issue by uhthomas** [dotdc/grafana-dashboards-kubernetes#80]
### Describe the bug

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/ceaf942b-cb68-4147-993e-5d2d81813bee)

### How to reproduce?

I don't know

### Expected behavior

The dashboard should not produce negative CPU usage values.

### Additional context

I adjusted some resource limits, which caused some pods to restart.

**Comment by uhthomas** [comment]
I don't really understand why.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/6920ff9d-d4e2-4b95-8914-fca68a5c6ce1)

**Comment by uhthomas** [comment]
Looks normal when switching the query to `avg(rate(node_cpu_seconds_total{mode!="idle"}[$__rate_interval]))`

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/6c78ec94-a803-467e-89fb-400d96591154)

versus

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/732c6e64-c586-4af5-b036-51c61385b967)

**Comment by dotdc** [comment]
Hi @uhthomas,
Thank you for opening this issue.
The values are quite different, did you compare them with other system tools or the metrics from the metrics-server (kubectl top)?

I will need to make some tests before approving your PR.

**Comment by jkroepke** [comment]
Hi,

I also read #80 and saw that the values are different between #80 and main branch. Based on this,  I do a research how other parties are doing CPU calculation:

<img width="1792" alt="image" src="https://github.com/dotdc/grafana-dashboards-kubernetes/assets/1560587/f69bf9c0-be53-41e8-90ec-c999aa63273d">

<details>
<summary>Dashboard to test on your own</summary>

```json
{
  "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "Prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "10.2.2"
    },
    {
      "type": "datasource",
      "id": "prometheus",
      "name": "Prometheus",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "${DS_PROMETHEUS}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "cellOptions": {
              "type": "auto"
            },
            "inspect": false
          },
          "decimals": 3,
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "percentunit"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 23,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "cellHeight": "sm",
        "footer": {
          "countRows": false,
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "frameIndex": 0,
        "showHeader": true
      },
      "pluginVersion": "10.2.2",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (instance) ",
          "format": "table",
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "main"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) by (instance)",
          "format": "table",
          "hide": false,
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "PR"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "avg(irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) by(instance)",
          "format": "table",
          "hide": false,
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "node_exporter_full"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])))",
          "format": "table",
          "hide": false,
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "Prometheus Alerts"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\",mode!=\"steal\"}[$__rate_interval]))",
          "format": "table",
          "hide": false,
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "kubernetes-mixin"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "1 - avg by (instance) (\n sum without (mode) (rate(node_cpu_seconds_total{mode=~\"idle|iowait|steal\"}[$__rate_interval]))\n)",
          "format": "table",
          "hide": false,
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "node-mixin R"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "editorMode": "code",
          "exemplar": false,
          "expr": "sum by (instance) (sum without(mode) (avg without (cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))))",
          "format": "table",
          "hide": false,
          "instant": true,
          "legendFormat": "__auto",
          "range": false,
          "refId": "node-mixin A"
        }
      ],
      "title": "Panel Title",
      "transformations": [
        {
          "id": "merge",
          "options": {}
        },
        {
          "id": "organize",
          "options": {
            "excludeByName": {
              "Time": true
            },
            "indexByName": {
              "Time": 0,
              "Value #PR": 2,
              "Value #Prometheus Alerts": 4,
              "Value #kubernetes-mixin": 8,
              "Value #main": 6,
              "Value #node-mixin A": 5,
              "Value #node-mixin R": 7,
              "Value #node_exporter_full": 3,
              "instance": 1
            },
            "renameByName": {}
          }
        }
      ],
      "type": "table"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "CPU test",
  "uid": "f551a6d1-ff6e-45b1-a7a0-84cf70124b75",
  "version": 1,
  "weekStart": ""
}
```

</details>

### main branch

```
avg(1-rate(node_cpu_seconds_total{mode="idle"}[$__rate_interval])) by (instance) 
```

### PR

```
avg(rate(node_cpu_seconds_total{mode!="idle"}[$__rate_interval])) by (instance)
```

### [node_exporter full](https://grafana.com/grafana/dashboards/1860-node-exporter-full/) dashboard is using

```
avg(irate(node_cpu_seconds_total{mode!="idle"}[$__rate_interval])) by(instance)
```

### [Awesome Prometheus alerts](https://samber.github.io/awesome-prometheus-alerts/rules.html#rule-host-and-hardware-1-15):

```
sum by (cluster, instance) (avg by (mode, cluster, instance) (rate(node_cpu_seconds_total{mode!="idle"}[$__rate_interval])))
```

### kubernetes-mixin

```
sum by (cluster,instance) (rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal"}[$__rate_interval]))
```

### node-mixin (official node_exporter)

[recording](https://github.com/prometheus/node_exporter/blob/73d95309e9632e42ba785703f534c7938630f2ec/docs/node-mixin/rules/rules.libsonnet#L18-L23) rule

```
1 - avg without (cpu) (
 sum without (mode) (rate(node_cpu_seconds_total{mode=~"idle|iowait|steal"}[$__rate_interval]))
)
```

[alerting](https://github.com/prometheus/node_exporter/blob/73d95309e9632e42ba785703f534c7938630f2ec/docs/node-mixin/alerts/alerts.libsonnet#L315C15-L315C161) rule

```
sum without(mode) (avg without (cpu) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) * 100
```

I could only do a test with an small subset of nodes:

<img width="1792" alt="image" src="https://github.com/dotdc/grafana-dashboards-kubernetes/assets/1560587/60985633-0301-4861-a139-61855bc1d795">


```
% k top node
NAME                               CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
aks-opsstack-21479518-vmss000000   258m         13%    3568Mi          28%       
aks-opsstack-21479518-vmss000001   643m         33%    7971Mi          64%  
```

**Comment by uhthomas** [comment]
Thanks for the comprehensive write up @jkroepke! It looks like this change is probably the right thing to do then?

With respect to kubectl top, I think it's known that these values can differ. I believe it's just the different time intervals and the way the metrics are collected?

**Comment by jkroepke** [comment]
At least the queries from #81 give me incorrect results

PR

<img width="886" alt="image" src="https://github.com/dotdc/grafana-dashboards-kubernetes/assets/1560587/d697e466-9455-47b6-823b-8dad94d131e9">

vs

```
# k top node
NAME                               CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
aks-opsstack-21479518-vmss000000   232m         12%    3619Mi          29%       
aks-opsstack-21479518-vmss000001   613m         32%    7920Mi          64%   
```

---

In my post before, I do more a brain dump of my findings.

**Comment by uhthomas** [comment]
I am not sure your evaluation is fair. They are taking measurements at different points in time and does not mean the query in #81 is incorrect. If it were, then all the dashboards you linked in your initial comment would also be wrong, which I don't believe is true.

**Comment by uhthomas** [comment]
I think the numbers look a bit weird because they are averaged, maybe not properly. The usage across cores varies quite widely:

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/e42c9c32-51d1-4563-a038-693ba8060429)

Averaged:

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/726589b3-09b6-4c31-88e6-c9871899df12)

**Comment by jkroepke** [comment]
> They are taking measurements at different points in time

Compared to `kubectl top`, yes.

But the queries from the dashboard based on the same datapoints. The dashboard on main branch show me 30%-35% CPU usage which is way more as the reported 4.2% from #81. The CPU on the system has a constant usage between 30%-35%. over hours. 4% is not possible. This is why, I declare the query as incorrect.

> If it were, then all the dashboards you linked in your initial comment would also be wrong, which I don't believe is true.

I would say 5 of 8 queries are true-ish. All values based on the exact same datapoints from different instances.

**Comment by uhthomas** [comment]
@jkroepke I do see what you mean. If you read my previous comment, it may best to calculate average cpu usage by core (`avg(sum by (cpu) (...))`). I can make this change in the PR and it should be more accurate. 

The query `avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!="idle"}[$__rate_interval])))`: 

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/0843d722-27c0-4dc2-b189-512b037f7142)

The other option is to change the graph to measure different CPU modes, or even cores? That wasn't really its intent though I guess.

**Comment by jkroepke** [comment]
> If you read my previous comment, it may best to calculate average cpu usage by core ...

Yeah, on the `Averaged by all` dashboard, you do `avg(rate(node_cpu_seconds_total{mode!="idle"}[$__rate_interval])) by (instance)`

This mean, an average of all CPU **modes**. If you have user 30% system 0% and iowait 0%, you have 30/3=10% CPU usage.

**Comment by uhthomas** [comment]
@jkroepke Agree. Would you be able to test the most recent changes in #81?

**Comment by jkroepke** [comment]
It looks much better now. 👍

**Comment by jkroepke** [comment]
FYI: While I do some research for the queries, I found https://github.com/prometheus/node_exporter/pull/2194.

I created a separate issue for this: https://github.com/dotdc/grafana-dashboards-kubernetes/issues/86

**Comment by dotdc** [comment]
This is an interesting discussion, I didn't have time to make some benchs, but It looks promising!

I tried the latest version and still see a big difference in the resulting values on my side (~ x3).
I will need to deep dive to make sure we get it right (most probably in January).

**Comment by jkroepke** [comment]
@dotdc please ensure that you are using the latest version of #81 because some queries where adjusted.

**Comment by dotdc** [comment]
> @dotdc please ensure that you are using the latest version of #81 because some queries where adjusted.

Yes it was the latest, CPU usage is 3x higher on the new version.
I'll need to check/compare to find which query is the closest to the reality.

**Comment by uhthomas** [comment]
> > @dotdc please ensure that you are using the latest version of #81 because some queries where adjusted.
> 
> 
> 
> Yes it was the latest, CPU usage is 3x higher on the new version.
> 
> I'll need to check/compare to find which query is the closest to the reality.

Would you be able to attach a screenshot? The amended query should be more accurate.

**Comment by dotdc** [comment]
![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/12827900/6aaebfed-b9ae-4042-88e1-c180199f8799)

As you can see, the values are quite different (at least on my side).
Comparing the results with trusted system tools or software can help I think.
I'm pretty sure I did that a long time ago, and it looked good to me, but maybe it's wrong...

We should definitely take the time to get this right.

PS: I don't think I will have time to look further before January :christmas_tree: :partying_face:

**Comment by uhthomas** [comment]
Thanks for your help @dotdc - that is interesting. I would be eager to see the individual values for the different modes on your cores. I wonder if the system is busy in the other idle states iowait and steal?

**Comment by dotdc** [comment]
Something like this?

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/12827900/ad641851-3583-4cf0-b81e-4bcb55996a5d)

**Comment by uhthomas** [comment]
Yes, exactly, but maybe with distinct colours for the values?

**Comment by dotdc** [comment]
This is the best I can do right now:

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/12827900/4188a859-fb48-4379-a2d7-47dcd622b601)

**Comment by uhthomas** [comment]
Again, appreciate your help. Enjoy your winter break @dotdc! 😄

**Comment by dotdc** [comment]
Thanks, you too!

**Comment by jkroepke** [comment]
> This is the best I can do right now:
> 
> ![image](https://private-user-images.githubusercontent.com/12827900/292585201-4188a859-fb48-4379-a2d7-47dcd622b601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODk1MzAsIm5iZiI6MTcwMzI4OTIzMCwicGF0aCI6Ii8xMjgyNzkwMC8yOTI1ODUyMDEtNDE4OGE4NTktZmI0OC00Mzc5LWEyZDctNDdkY2Q2MjJiNjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIzNTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NTU3NjFiNWQ1ZGNiYTAxMTY0NmNjMjc3ODc3OTI3ZGU4MTQ0NWNmYTE0MmIxZTBlNThiNGRkMDRmZTRlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zCqjsf-jRhY25SUBpDCsCw6dmnLkmDP5KJO87pEy4Lo)

Could you please this, without excluding iowait and steal?

**Comment by uhthomas** [comment]
This query could possibly be helpful? If there is a lot of cpu time spent on steal or iowait, then it would make sense that comparing to just idle would produce a wildly different graph.

```
avg by (mode) (node_cpu_seconds_total{mode=~"steal|iowait"})
```

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/f7fe5e72-e409-4b63-b1f8-178ab20c2b2a)

I have a feeling the new query is a more accurate representation of actual CPU usage - but the graphs shown [here](https://github.com/dotdc/grafana-dashboards-kubernetes/issues/80#issuecomment-1868048552) look very suspect.

The same graph on my cluster also shows discrepancies (as expected), but not to such huge degrees.

(new on bottom)

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/733417c5-c529-4a09-b2ad-3f3c96f772a7)

**Comment by uhthomas** [comment]
Please also see these dashboards side-by-side. The first one is the original, the second matches everything but "idle" and the third one is the current query which matches everything but "idle", "iowait" and "steal". The final graph shows CPU usage across the whole cluster by namespace. There is a clear discrepancy, and the third graph seems the most accurate to me.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/1368f8ff-e788-402c-afc5-db1c974ca756)

For context, there are 20 allocatable cpus on the cluster. I do not see how 50% utilisation could ever make sense.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/c780b0b3-d6b7-4dac-a50f-c983916f3e63)


The following is the same as the original image, but with stacked cpu usage to demonstrate that a value of 50% is unrealistic.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/8d9a1690-68bf-4276-a88b-882731c210cb)

**Comment by uhthomas** [comment]
This final image may also be helpful. It shows there was a spike in iowait, which is not currently accounted for.

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/6adb6637-7b92-44cc-a5b3-7bbc16267fd6)

**Comment by dotdc** [comment]
Hi @uhthomas,

I made a limited number of additional tests this morning. 
Your query is good on the nodes dashboard, but the differences from my previous screenshots remains on the global view.

I've managed to get closer to your values by dividing the result by the number of nodes.

```
avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~"idle|steal|iowait", cluster="$cluster"}[$__rate_interval]))) / count(count by (node) (kube_node_info{cluster="$cluster"}))
```

This should work for clusters that have homogenous nodes flavors across nodepools, but I have concerns on clusters that have heterogenous nodepools/flavors.

Could you double-check this on your setup?
Also, do you have a cluster with different node flavors to see how this behaves?

Screenshot:
![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/12827900/126def46-1d37-4f01-920a-dfed977f35f0)

**Comment by uhthomas** [comment]
@dotdc I am currently running a single node Kubernetes cluster, I was not aware of this limitation. I imagine what's happening here is it should be `sum by (node, cpu)`. I can fix this when I get back later, and should resolve the issue you're seeing 😄

**Comment by uhthomas** [comment]
Would you be able to test it for me in the meantime?

**Comment by uhthomas** [comment]
I've updated the PR @dotdc

**Comment by dotdc** [comment]
This was great, thank you both @uhthomas & @jkroepke !
