### ISSUE TITLE
All dashboards with cluster variable is broken in VictoriaMetrics [bug] 

### ISSUE THREAD

**Issue by Krelion** [dotdc/grafana-dashboards-kubernetes#83]
### Describe the bug

Popup message in grafana when opening dashboards:

Templating
Failed to upgrade legacy queries Datasource prometheus was not found

Previsious version working fine

### How to reproduce?

Install VictoriaMetrics as prometheus datasource and try open namespace dashboard

### Expected behavior

Dashboards works correctly

**Comment by dotdc** [comment]
Hi @Krelion,

Thank you for reporting the issue, this bug was introduced by changes made yesterday. 
Just merged #84, could you try the latest version and let me know if it works on your VictoriaMetrics setup?

**Comment by Krelion** [comment]
Everything works well, thanks!

**Comment by Krelion** [comment]
Can you add tags for new versions so that our code can reference the exact version?

**Comment by dotdc** [comment]
You mean manage a release for the entire set using git tags?

**Comment by Krelion** [comment]
> You mean manage a release for the entire set using git tags?

yes

**Comment by dotdc** [comment]
Sure, I can do that. Can you use `master` in the meantime?
I'll close this issue as the bug is fixed, but I will notify you when the release/tagging workflow will be available.
