### ISSUE TITLE
[bug] should use last non-null value, rather than mean

### ISSUE THREAD

**Issue by uhthomas** [dotdc/grafana-dashboards-kubernetes#88]
### Describe the bug

3/4 of these guages use the mean, rather than the last non-null value. This can cause strangeness like incorrect reporting of current cpu requests and limits. They should also be consistent.

Current:

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/6e460390-36f4-44ac-b688-9b7e6ad43047)

Last *:

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/9749173/9151a5ba-327e-4ea3-84ee-d0b39d7d6a6a)

### How to reproduce?

1. Observe the global view
2. Change some cpu requests and limits
3. Observe incorrect reporting of cpu requests and limits

### Expected behavior

Should probably use "Last *" rather than "Mean" for calculating the value.

**Comment by dotdc** [comment]
Hi @uhthomas,

Yes, definitely a mistake!
Do you want to make a PR, or should I do it?

**Comment by dotdc** [comment]
Should be good now @uhthomas, thanks for reporting !
