### ISSUE TITLE
Metrics missing in K8s Environment

### ISSUE THREAD

**Issue by i5Js** [dotdc/grafana-dashboards-kubernetes#9]
I've opened a new issue because this one is not in the k3s environment but k8s.

I see some metrics missing, probably because my installation could be incomplete. 
I've deployed the k8s cluster, with two masters and three workers nodes. Grafana and prometheus are deployed with "almost" de default settings.

```
i5Js@nanoserver:~/K3s/K8s/grafana/grafana-dashboards-kubernetes/dashboards$ k get svc -n grafana
NAME      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
grafana   ClusterIP   <ip>   <none>        80/TCP    18h
```

```
i5Js@nanoserver:~/K3s/K8s/grafana/grafana-dashboards-kubernetes/dashboards$ k get svc -n prometheus
NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
prometheus-alertmanager         ClusterIP   <ip>     <none>        80/TCP     21h
prometheus-kube-state-metrics   ClusterIP   <ip>     <none>        8080/TCP   21h
prometheus-node-exporter        ClusterIP   <ip>     <none>        9100/TCP   21h
prometheus-pushgateway          ClusterIP   <ip>    <none>        9091/TCP   21h
prometheus-server               ClusterIP   <ip>    <none>        80/TCP     21h
```

I've created the datasource using the prometheus-server ip, and some of the metrics works and some don't:

<img width="1372" alt="Screenshot 2022-07-02 at 10 08 38" src="https://user-images.githubusercontent.com/1070363/176992442-d3fc8938-e6d0-475d-9b45-a0c68e2a9250.png">

<img width="1370" alt="Screenshot 2022-07-02 at 10 10 16" src="https://user-images.githubusercontent.com/1070363/176992473-b2b916f0-4e27-40e5-bc23-ea875e28880b.png">

I'm completely sure that those issues are because my environment because I see that your dashboards work fine, but, can you help me troubleshoot?

Thanks,

**Comment by dotdc** [comment]
Hi @i5Js,

Sorry I will not provide support on your setup, but you should check the logs, the exporters, prometheus configuration and  targets status...

Also, you could use [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to deploy everything (prometheus, prometheus-operator, grafana, exporters....), and it should work out of the box.

Will be happy to help if you have issues related to theses dashboards.

Good luck :)

**Comment by i5Js** [comment]
I'm not trying to get support on my setup, but It surprises  me that you think your deployment is "perfect" 
It's clear something changed in the new releases of Prometheus and/or grafana and probably you don't know either.

**Comment by dotdc** [comment]
HI @i5Js,

I didn't say or think that my deployment is perfect, there could be many diverse setups and theses dashboards will not fit them all for sure.
I just said that I only planned to support kube-prometheus-stack for now, and will make it clear in a CONTRIBUTING.md.

As I don't use the latest prometheus version, maybe you're right, will check and get back to you.
But if you have a patch that you think is compatible with kube-prometheus-stack, feel free to make a pull request.

David
