### ISSUE TITLE
[bug] Trivy Dashboard Templating Failed to upgrade legacy queries Datasource prometheus was not found

### ISSUE THREAD

**Issue by marcofranssen** [dotdc/grafana-dashboards-kubernetes#94]
### Describe the bug

The trivy dashboard breaks since this commit https://github.com/dotdc/grafana-dashboards-kubernetes/commit/4b52d9cb916eafceae71da6efd15ed29d9d4404c on our clusters.

### Expected behavior

The dashboard continues to work like on the commit before. Other dashboards don't seem to have this issue.

### Additional context

Is there any chance it is because of the missing cluster label on trivy metrics? Should we configure a specific setting to include this cluster label on the trivy operator?

**Comment by dotdc** [comment]
Hi @marcofranssen,

It works on my side (even with an empty cluster label), so something must be different...
Could you please explain what doesn't work and give some information on your setup and data (explore, probably look the cluster label)?
