### ISSUE TITLE
Question: How I should export dashboard json

### ISSUE THREAD

**Issue by jkroepke** [dotdc/grafana-dashboards-kubernetes#97]
Hi,

I'm prepare #79 and I have some trouble to export the JSON file a grafana instance.

If I import a dashboard and export again without any modifications, I get a lot of changes:

For example this commit does not contain any changes, from a lot of changes of JSON level: https://github.com/jkroepke/grafana-dashboards-kubernetes/commit/706315bc38eb2a4aa3145073d1b50c52ad5900ef

Thats how I export the JSON

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/1560587/4d8b2073-d0f3-47eb-bbec-902a42d33cec)

What the recommend way? If the mention approch is the correct one, would it be possible to import and export all dashboard the keep my PR clean as possible? Otherwise, I had tons of non related changes.

**Comment by dotdc** [comment]
Hi @jkroepke,
Unfortunately, I don't know a way of doing that easily...
I generally use `Dashboard settings` -> `JSON Model`, but you'll still need to make some changes:
- Add back the header for Grafana.com (`__inputs`, `__elements`, `__requires`...)
- remove `id` and other instance related fields (if any)
- Remove any changes to dashboard variables selection (if any)
- Bump the dashboard version (previous +1)

Please use the latest version of Grafana to edit the dashboards, as API is automatically updated. You'll still see other changes, but they should be fine.

Start with one, and I'll review it to make sure it's fine.

Hope it helps

**Comment by dotdc** [comment]
You also need to keep
> "uid": "${datasource}"

instead of:
>  "uid": "${DS_PROMETHEUS}"
